#ifndef __RT_AI_WAVMODEL_MODEL_H
#define __RT_AI_WAVMODEL_MODEL_H

#include <wavmodel.h>
#include <wavmodel_data.h>

/* model info ... */

// model name
#define RT_AI_WAVMODEL_MODEL_NAME			"wavmodel"
#define RT_AI_WAVMODEL_WORK_BUFFER_BYTES		AI_WAVMODEL_DATA_ACTIVATIONS_SIZE
#define RT_AI_WAVMODEL_DATA_WEIGHTS_SIZE		AI_WAVMODEL_DATA_WEIGHTS_SIZE

#define RT_AI_WAVMODEL_BUFFER_ALIGNMENT		AI_WAVMODEL_ACTIVATIONS_ALIGNMENT

#define RT_AI_WAVMODEL_IN_NUM				AI_WAVMODEL_IN_NUM
#define RT_AI_WAVMODEL_IN_1_SIZE				AI_WAVMODEL_IN_1_SIZE
#define RT_AI_WAVMODEL_IN_1_SIZE_BYTES		AI_WAVMODEL_IN_1_SIZE_BYTES
#define RT_AI_WAVMODEL_IN_TOTAL_SIZE_BYTES	(AI_WAVMODEL_IN_1_SIZE_BYTES)
#define RT_AI_WAVMODEL_IN_SIZE_BYTES			{AI_WAVMODEL_IN_1_SIZE_BYTES}


#define RT_AI_WAVMODEL_OUT_NUM				AI_WAVMODEL_OUT_NUM
#define RT_AI_WAVMODEL_OUT_1_SIZE			AI_WAVMODEL_OUT_1_SIZE
#define RT_AI_WAVMODEL_OUT_1_SIZE_BYTES		AI_WAVMODEL_OUT_1_SIZE_BYTES
#define RT_AI_WAVMODEL_OUT_TOTAL_SIZE_BYTES	(AI_WAVMODEL_OUT_1_SIZE_BYTES)
#define RT_AI_WAVMODEL_OUT_SIZE_BYTES		{AI_WAVMODEL_OUT_1_SIZE_BYTES}


#define RT_AI_WAVMODEL_TOTAL_BUFFER_SIZE		(NULL)		//unused

#endif	//end
